### PR TITLE
Fixes add listeners before connecting to drachtio

### PR DESCRIPTION
**Pull request by joelact**
This PR fixes the issue described on #79

### CODE REVIEW

**Comment by davehorton** [comment]
Thanks.  Can you give me an idea of the scenario you experienced where this would fix?

**Comment by joelact** [comment]
> Thanks. Can you give me an idea of the scenario you experienced where this would fix?

It's the same scenario described in issue #79. @alexandremiguelabreu and I are working on the same project so we came up with this fix.

I hope this answers your question.

**Comment by davehorton** [comment]
OK, this looks good to me.  Did you test to make sure that when you call things in this order:

```
srf.on('cdr:attempt', ..);
srf.connect(..
```
that you do in fact get cdr events?

**Comment by joelact** [comment]
> OK, this looks good to me. Did you test to make sure that when you call things in this order:
> 
> ```
> srf.on('cdr:attempt', ..);
> srf.connect(..
> ```
> 
> that you do in fact get cdr events?

I did the test manually and checked that the events were being received.

**Pull request merged**
